name: "Thermostat Manager"
description: "Zentrale Steuerung von Homematic IP Thermostaten mit globalem Temperatur-Offset"
version: "1.0.5"
slug: "thermostat_manager"
init: false
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
homeassistant_api: true
host_network: false
ingress: true
ingress_port: 5000
panel_icon: "mdi:thermostat"
panel_title: "Thermostat Manager"
ports:
  5000/tcp: null
ports_description:
  5000/tcp: "Web interface (disabled when using Ingress)"
